import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { QueryClientProvider } from "@/components/providers/QueryClientProvider";
import { Toaster } from "@/components/ui/toast";
import AuthSessionProvider from "@/components/providers/AuthSessionProvider";
import { Toaster as SonnerToaster } from "sonner";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans")}>
      <body
        className={` antialiased`}
      >
        <QueryClientProvider>
          <Toaster richColors position="top-right" />
          <SonnerToaster richColors position="top-right" />
           <AuthSessionProvider>{children}</AuthSessionProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
